### PR TITLE
Add minimal conda environment to run repo code

### PR DESCRIPTION
**Pull request by kaedonkers**
- Add `environment.yml` with minimal package spec for project
- Add instructions to README.md on how to create and use Conda environment

### CODE REVIEW

**Comment by kaedonkers** [comment]
@ben18785 is what you had in mind?

**Comment by ben18785** [comment]
Thanks @kaedonkers -- that's awesome and really helpful for people (me included!).

The other thing(s) I was hoping we could add were step by step tutorial-like steps as I put in [this repo](https://github.com/open-courses-statistics-data-science/pipeline_tools_targets) including what commands to execute to get snakemake to do stuff (via the terminal or otherwise? I've not used it). Part of the reason is that I have found the [Snakemake tutorials](https://snakemake.readthedocs.io/en/stable/tutorial/short.html) to be long winded and not helpful for quickly getting up and running and doing basic data analyses.

**Comment by kaedonkers** [comment]
Yep, that's fair - docs weren't the clearest on how to do that. If you're happy to merge this PR I'll open a new one to add basic Snakemake instructions

**Review by ben18785 — APPROVED** [review]
Cheers -- merging now

**Comment by kaedonkers** [comment]
Thanks! :)

**Pull request merged**
