### PR TITLE
Basic instructions on how to execute and visualise Snakemake pipeline

### PR DESCRIPTION
**Pull request by kaedonkers**

### CODE REVIEW

**Comment by kaedonkers** [comment]
@ben18785 How's that for a starter? I think it could do with some expansion but these were the basic commands I used to execute the whole pipeline and visualise it.

**Review by ben18785 — APPROVED** [review]
Thanks @kaedonkers -- this is great: I just tried this and worked really nicely.

One thing: I needed to install graphviz via `brew install graphviz`. Do we need to add this to the conda environment or not? Sorry not an expert in these things

**Comment by kaedonkers** [comment]
Good catch - I can indeed add it to the conda spec, will include in this PR

**Review by ben18785 — APPROVED** [review]
Thanks @kaedonkers -- looks grant. Merging in now

**Pull request merged**
